package com.checkout.payment.gateway.service;

import com.checkout.payment.gateway.client.BankClient;
import com.checkout.payment.gateway.enums.Currency;
import com.checkout.payment.gateway.enums.PaymentStatus;
import com.checkout.payment.gateway.exception.EventProcessingException;
import com.checkout.payment.gateway.model.BankPaymentResponse;
import com.checkout.payment.gateway.model.PostPaymentRequest;
import com.checkout.payment.gateway.model.PostPaymentResponse;
import com.checkout.payment.gateway.repository.PaymentsRepository;
import com.checkout.payment.gateway.util.CardUtils;
import java.time.YearMonth;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

/**
 * Service for query payment information and process payment
 */
@Service
public class PaymentGatewayService {

  private static final Logger LOG = LoggerFactory.getLogger(PaymentGatewayService.class);

  private final PaymentsRepository paymentsRepository;
  private final BankClient bankClient;

  public PaymentGatewayService(PaymentsRepository paymentsRepository, BankClient bankClient) {
    this.paymentsRepository = paymentsRepository;
    this.bankClient = bankClient;
  }

  /**
   * Return payment information by payment id,
   * returned and generated by payment gateway.
   * @param id
   * @return payment info
   */
  public PostPaymentResponse getPaymentById(UUID id) {
    LOG.debug("Requesting access to to payment with ID {}", id);
    return paymentsRepository.get(id).orElseThrow(() -> new EventProcessingException("Invalid ID"));
  }

  /**
   * Process payment from merchant and send to bank,
   * finally save the result to local repo layer.
   * @param paymentRequest
   * @return postPaymentResponse
   */
  public PostPaymentResponse processPayment(PostPaymentRequest paymentRequest) {
    PostPaymentResponse response = createPaymentResponse(paymentRequest);

    // check parameyers
    if (!isValid(paymentRequest)) {
      response.setStatus(PaymentStatus.REJECTED);
      paymentsRepository.save(response);
      return response;
    }

    // call bank client
    BankPaymentResponse bankResponse = bankClient.processPayment(paymentRequest);
    if (bankResponse == null) {
      response.setStatus(PaymentStatus.REJECTED);
    } else {
      response.setStatus(bankResponse.isAuthorized()
          ? PaymentStatus.AUTHORIZED
          : PaymentStatus.DECLINED);
    }
    paymentsRepository.save(response);
    return response;
  }

  /**
   * Method for creating payment response object.
   * @param paymentRequest
   * @return boolean
   */
  private PostPaymentResponse createPaymentResponse(PostPaymentRequest paymentRequest) {
    PostPaymentResponse response = new PostPaymentResponse();
    response.setId(UUID.randomUUID());
    response.setCardNumberLastFour(CardUtils.getCardNumberLastFourAsInt(paymentRequest.getCardNumber()));
    response.setExpiryMonth(paymentRequest.getExpiryMonth());
    response.setExpiryYear(paymentRequest.getExpiryYear());
    response.setCurrency(paymentRequest.getCurrency());
    response.setAmount(paymentRequest.getAmount());
    return response;
  }

  /**
   * Check whether the input is valid
   * @param paymentRequest
   * @return boolean
   */
  private boolean isValid(PostPaymentRequest paymentRequest) {
    return isValidCardNumber(paymentRequest.getCardNumber())
        && isValidCvv(paymentRequest.getCvv())
        && isValidExpiryDate(paymentRequest.getExpiryMonth(), paymentRequest.getExpiryYear())
        && isValidCurrency(paymentRequest.getCurrency())
        && paymentRequest.getAmount() > 0;
  }

  /**
   * The length of card number should be in 14 to 19 digits.
   * @param cardNumber
   * @return boolean
   */
  private boolean isValidCardNumber(String cardNumber) {
    return cardNumber != null && cardNumber.matches("\\d{14,19}");
  }

  /**
   * The length of cvv should be in 3 to 4 digits.
   * @param cvv
   * @return
   */
  private boolean isValidCvv(String cvv) {
    return cvv != null && cvv.matches("\\d{3,4}");
  }

  /**
   * Expiry Month and Year should be after this year and month
   * @param expiryMonth
   * @param expiryYear
   * @return valid or not
   */
  private boolean isValidExpiryDate(int expiryMonth, int expiryYear) {
    if (expiryMonth < 1 || expiryMonth > 12) {
      return false;
    }
    return YearMonth.of(expiryYear, expiryMonth).isAfter(YearMonth.now());
  }

  /**
   * The type of currency should be allowed
   * @param currency
   * @return boolean
   */
  private boolean isValidCurrency(String currency) {
    return Currency.isSupported(currency);
  }
}
